version: 2

references:

  workspace_root: &workspace_root
      ~/code

  container_config: &container_config
    xcode:
      version: "9.1"

    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: *workspace_root

    environment:
      JVM_OPTS: -Xmx3200m

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

  general_cache_key: &general_cache_key
      key: chinese-{{ checksum "build.gradle" }}-{{ checksum ".circleci/config.yml" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}

jobs:

  build:
    <<: *container_config
    steps:
      - checkout

      - restore_cache:
          <<: *general_cache_key
      - run: ./gradlew dependencies
      - save_cache:
          <<: *general_cache_key
          paths:
            - ~/.gradle
            - ~/.m2

      - run: ./gradlew clean
      - run: ./gradlew assemble
      - run: ./gradlew createEngine
      - run: ./gradlew cobertura
      - run: ./gradlew findbugsMain
      - run: ./gradlew checkstyleMain

      - store_test_results:
          path: build/test-results
      - store_artifacts:
          path: build/reports
          destination: reports
      - store_artifacts:
          path: build/cobertura
          destination: reports/cobertura
